# Change these first
owner: victorposada # Your GitHub organization or username, where this repository lives
repo: vsh-upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Google DNS 
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    icon: https://www.google.com/favicon.ico
  - name: Cludflare
    url: https://www.cloudflare.com
  - name: Cloudflare DNS 
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
    icon: https://www.cloudflare.com/favicon.ico
  - name: Cisco
    url: https://www.cisco.com
  - name: Cisco DNS 
    check: "tcp-ping"
    url: 208.67.222.222
    port: 53
    icon: https://www.cisco.com/favicon.ico


status-website:
  baseUrl: /vsh-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VSH website monitoring
  theme: light
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/victorposada/vsh-upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /vsh-upptime
    - title: GitHub
      href: https://github.com/victorposada/vsh-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
